import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Slider from "../components/Slider";
import Crousel from "../components/Crousel";
import birds from "../images/birds.svg";
import sliderStyles from "../styles/Slider.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <div
        className="relative "
        style={{ height: "978px", background: "#EFEFEF" }}
      >
        <img src={birds.src} className="absolute z-10 ml-60 mt-16"></img>
        <div className={sliderStyles.wrap}>
          <div className={sliderStyles.box}></div>
        </div>
        <div className={styles.section_2 + "h-96"}>
          <Slider />
        </div>
      </div>
      <Crousel />
    </div>
  );
}
